# Run the security scan (psalm) on a REDCap External Module

name: REDCap External Module Security Scan

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      RC_COMMUNITY_USERNAME:
        type: string
        required: true
      RC_SCAN_VERSION:
        type: string
        required: false
      RC_SYSTEM_HOOKS:
        type: boolean
        default: false
        required: false
    secrets:
      RC_COMMUNITY_PASSWORD:
        required: true

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Get latest REDCap version number
        env:
          redcap_scan_version: ${{ inputs.RC_SCAN_VERSION }}
        run: |
          scan_version=$(echo "$redcap_scan_version" | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          if [[ ${#scan_version} < 5 ]]; then
            wget -O ~/redcap_version.json https://redcap.vumc.org/plugins/redcap_consortium/versions.php
            redcap_version=$(jq -r '.latest_version' ~/redcap_version.json)
            echo "redcap_version=$redcap_version" >> $GITHUB_ENV
            rm ~/redcap_version.json
          else
            redcap_version="$scan_version"
          fi

      - name: Restore REDCap zip for version ${{ env.redcap_version }}
        id: cache-redcap
        uses: actions/cache/restore@v4
        with:
          path: ~/redcap.zip
          key: redcap-${{ env.redcap_version }}

      - name: Download latest REDCap version
        if: steps.cache-redcap.outputs.cache-hit != 'true'
        env:
          rcc_user: ${{ inputs.RC_COMMUNITY_USERNAME }}
          rcc_pass: ${{ secrets.RC_COMMUNITY_PASSWORD }}
        run: |
          # Download REDCap.
          wget -q --post-data="version=${redcap_version}&install=1&username=${rcc_user}&password=${rcc_pass}" -O ~/redcap.zip https://redcap.vumc.org/plugins/redcap_consortium/versions.php
          # If download size less than 10MB, assume an error has occurred and exit.
          if [ $(stat -c%s ~/redcap.zip) -lt 10000000 ]; then
            exit 1
          fi

      - name: Cache REDCap zip for version ${{ env.redcap_version }}
        if: steps.cache-redcap.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/redcap.zip
          key: redcap-${{ env.redcap_version }}

      - name: Extract REDCap
        run: |
          mkdir ~/redcap
          unzip -q -d ~/redcap ~/redcap.zip

      - name: Set REDCap DB Connection values
        run: |
          echo '<?php' > ~/redcap/redcap/database.php
          echo 'global $log_all_errors; $log_all_errors = false;' >> ~/redcap/redcap/database.php
          echo '$hostname = "127.0.0.1"; $db = "redcap"; $username = "root"; $password = "root";' >> ~/redcap/redcap/database.php
          echo '$db_ssl_key = ""; $db_ssl_cert = ""; $db_ssl_ca = ""; $db_ssl_capath = null; $db_ssl_cipher = null; $db_ssl_verify_server_cert = false;' >> ~/redcap/redcap/database.php
          echo '$salt = "abc123";' >> ~/redcap/redcap/database.php

      - name: Upgrade PHP
        run: |
          # Uninstall the provided PHP version and replace it with the latest release of the second newest minor version.
          installed_php_ver_full=$(php -v | head -n 1 | cut -d " " -f 2)
          installed_php_ver=$(echo "$installed_php_ver_full" | cut -f1-2 -d".")
          sudo apt-get purge "php${installed_php_ver}-amqp" "php${installed_php_ver}-apcu" "php${installed_php_ver}-dba" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-dev" "php${installed_php_ver}-enchant" "php${installed_php_ver}-imap" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-igbinary" "php${installed_php_ver}-interbase" "php${installed_php_ver}-mongodb" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-odbc" "php${installed_php_ver}-pcov" "php${installed_php_ver}-pgsql" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-phpdbg" "php${installed_php_ver}-pspell" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-redis" "php${installed_php_ver}-snmp" "php${installed_php_ver}-sqlite3" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-sybase" "php${installed_php_ver}-tidy" "php${installed_php_ver}-xdebug" > /dev/null || true
          sudo apt-get purge "php${installed_php_ver}-xsl" "php${installed_php_ver}-yaml" "php${installed_php_ver}-zmq" > /dev/null || true
          installed_php=($(dpkg -l | awk '/^ii/ && $2 ~ /^php[0-9]/ {print $2}'))
          declare -a installed_php_pkgs=()
          for pkg in "${installed_php[@]}"; do
            if [[ "$pkg" =~ ^php${installed_php_ver}- ]]; then
              installed_php_pkgs+=("${pkg#php${installed_php_ver}-}")
            fi
          done
          echo "Uninstalling PHP ${installed_php_ver_full}"
          sudo apt-get purge "php${installed_php_ver}" "php${installed_php_ver}-*" > /dev/null || true
          sudo add-apt-repository ppa:ondrej/php > /dev/null
          sudo apt-get update > /dev/null
          php_versions=($(apt-cache search ^php[0-9]\\.[0-9]$ | awk '{print $1}' | sed 's/php//' | sort -t. -k1,1n -k2,2n))
          echo "Installing PHP ${php_versions[-2]}"
          package="php${php_versions[-2]}"
          sudo NEEDRESTART_SUSPEND=1 apt-get install "$package" > /dev/null || sudo NEEDRESTART_SUSPEND=1 apt-get install "$package" > /dev/null
          for pkg in "${installed_php_pkgs[@]}"; do
            echo " - extension ${pkg}"
            sudo NEEDRESTART_SUSPEND=1 apt-get install "${package}-${pkg}" > /dev/null || sudo NEEDRESTART_SUSPEND=1 apt-get install "${package}-${pkg}" > /dev/null
          done

      - name: Start MySQL and create REDCap database
        run: |
          # Start MySQL and create REDCap database.
          export MYSQL_PWD="root"
          echo "MYSQL_PWD=$MYSQL_PWD" >> $GITHUB_ENV
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE redcap;' -uroot

      - name: Run installation SQL files
        run: |
          mysql -uroot redcap < ~/redcap/redcap/redcap_v${{ env.redcap_version }}/Resources/sql/install.sql
          mysql -uroot redcap < ~/redcap/redcap/redcap_v${{ env.redcap_version }}/Resources/sql/install_data.sql
          mysql -e 'UPDATE redcap_config SET value = '\''${{ env.redcap_version }}'\'' WHERE field_name = '\''redcap_version'\'';' -uroot redcap
          mysql -e 'REPLACE INTO redcap_history_version (`date`, redcap_version) VALUES (curdate(),'\''${{ env.redcap_version }}'\'');' -uroot redcap

      - name: Install scan script
        run: |
          # Create bin directory and install scan script.
          mkdir ~/redcap/redcap/bin
          echo '#!/usr/bin/env php' > ~/redcap/redcap/bin/scan
          echo '<?php' >> ~/redcap/redcap/bin/scan
          echo 'require_once __DIR__ . "/../redcap_connect.php";' >> ~/redcap/redcap/bin/scan
          echo 'require_once APP_PATH_EXTMOD . "bin/scan.php";' >> ~/redcap/redcap/bin/scan
          chmod 0755 ~/redcap/redcap/bin/scan
          # Suppress quiet instruction in 'composer install' in scan script.
          sed -i -e 's/php $composerPath install -q/php $composerPath install/' ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/classes/Scan.php
          # Write a composer.json in the ExternalModules directory if it is missing.
          if [ ! -f "$HOME/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json" ]; then
            echo '{' > ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '    "require-dev": {' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "phpcompatibility/php-compatibility": "10.0.0-alpha2",' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "johnkary/phpunit-speedtrap": "*",' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "vimeo/psalm": "^6",' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "phpunit/phpunit": "^9",' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "squizlabs/php_codesniffer": "^3",' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "friendsofphp/php-cs-fixer": "^3.86"' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '    },' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '    "config": {' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "platform": {' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '            "php": "8.1.31"' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        },' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        "allow-plugins": {' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '            "dealerdirect/phpcodesniffer-composer-installer": false' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '        }' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '    }' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
            echo '}' >> ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/composer.json
          fi

      - name: Suppress errors for system hooks
        if: inputs.RC_SYSTEM_HOOKS
        run: sed -i -e 's/$warningDisplayed = true;//' ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/classes/Scan.php

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install any composer dependencies
        run: |
          if [ -f "composer.lock" ]; then
            composer install
          fi

      - name: Run psalm scan
        run: |
          echo "psalm_started=1" >> $GITHUB_ENV
          ~/redcap/redcap/bin/scan --output=html-file ./

      - name: Get file name and date
        if: (success() || failure()) && env.psalm_started == '1'
        run: |
          psalm_output=$(ls redcap-scan_*.html)
          echo "psalm_output=$psalm_output" >> $GITHUB_ENV
          psalm_output_json=$(echo "$psalm_output" | sed 's/.html$/.json/')
          echo "psalm_output_json=$psalm_output_json" >> $GITHUB_ENV
          touch "$psalm_output_json"
          current_date=$(date -u +%F-%H-%M)
          echo "current_date=$current_date" >> $GITHUB_ENV

      - name: Psalm scan json output
        if: (success() || failure()) && env.psalm_started == '1'
        run: |
          sed -i 's/--debug/--output-format=json/g' ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/bin/scan.php
          sed -i 's/--debug/--output-format=json/g' ~/redcap/redcap/redcap_v${{ env.redcap_version }}/ExternalModules/classes/Scan.php
          ( ~/redcap/redcap/bin/scan ./ --output-format=json | jq >${{ env.psalm_output_json }} 2>/dev/null ) || true

      - name: Store output as artifact
        if: (success() || failure()) && env.psalm_started == '1'
        uses: actions/upload-artifact@v4
        with:
          name: redcap_scan_output_${{ env.current_date }}
          path: |
            ${{ env.psalm_output }}
            ${{ env.psalm_output_json }}

